name: Elixir Test and format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "25.x"
          elixir-version: "1.16.x"

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test

      - name: Check code formatting
        run: mix format --check-formatted
